GET {{$dotenv API_BASE_URL}}/customers/

###

GET {{$dotenv API_BASE_URL}}/customers/names

###

POST {{$dotenv API_BASE_URL}}/customers/
Content-Type: application/json

{
    "customer": {
        "name": "alt die inc.{{$timestamp }}",
        "type": "customer"
    }
}