GET {{$dotenv API_BASE_URL}}/customers/

###

GET {{$dotenv API_BASE_URL}}/customers/names

###

POST {{$dotenv API_BASE_URL}}/customers/
Content-Type: application/json

{
    "customer": {
        "name": "Alternative Die Cutting Inc.",
        "type": "supplier",
        "contacts":[
            {
                "type": "email",
                "label": "Richard",
                "info":"richard@alternativedc.com"
            },
            {
                "type": "email",
                "label": "Rob",
                "info":"rob@alternativedc.com"
            },
            {
                "type": "email",
                "label": "Frank",
                "info":"frankp@alternativedc.com"
            },
            {
                "type": "email",
                "label": "Carmine",
                "info":"carmine@alternativedc.com"
            },
            {
                "type": "email",
                "label": "Aldo",
                "info":"aldo@alternativedc.com"
            },
            {
                "type": "email",
                "label": "Shipping",
                "info":"shipping@alternativedc.com"
            },
            {
                "type": "email",
                "label": "Dies",
                "info":"dies@alternativedc.com"
            },
            {
                "type": "email",
                "label": "Developer",
                "info":"developer@alternativedc.com"
            }
        ]
    }
}

###

POST {{$dotenv API_BASE_URL}}/user/signup
Content-Type: application/json

{
    "user": {
        "email": "test@123.com",
        "password": "Password!2",
        "username": "1"
    }
}

###

POST {{$dotenv API_BASE_URL}}/user/signin
